### ISSUE TITLE
Create desktop version.

### ISSUE THREAD

**Issue by AmitJoki** [gskinner/regexr#26]
I find the desktop app very useful. The web version with new UI is awesome. Can you please update the Adobe Air app as well?

**Comment by TechnikEmpire** [comment]
http://www.tidesdk.org/

**Comment by wdamien** [comment]
We have looked into tidesdk, but unfortunately the project has been dead for a while.  It looks like the tidesdk team is now focussed on building https://www.tidekit.com/

**Comment by TechnikEmpire** [comment]
Yeah it's not really dead, they just abandoned it to make tidekit, because they failed to commercialize tidesdk. Tidesdk works fine, it just uses webkit, whereas tidekit is using chromium embedded framework. I think tidesdk would handle the task of wrapping your website fine. As an alternative, you could always whip something up in mono using CEF, as the is a .net wrapper. You'd then have a cross platform native application.

**Comment by TechnikEmpire** [comment]
Sorry I should correct my last statement: you're right in saying it's dead, in the sense that development has ceased. A halt in development doesn't equate to the project being useless, it what I meant to say.

**Comment by TechnikEmpire** [comment]
There is also adobe brackets which could be adapted to be a shell for the application, http://brackets.io. You might even be able to just extend it via plugins, since it's already an editor.

**Comment by wdamien** [comment]
yes, I did mean dead in the sense that development has stopped. But I'm also thinking towards the future, and it doesn't make sense to use a framework that will never be updated again. Any language or framework could die :) But something that obviously has no future is just not worth the time imho. Especially with so many great alternatives out there.

**Comment by TechnikEmpire** [comment]
Well it doesn't really seem that there are too many great alternatives out there, since you have nearly a years worth of community suggestions and requests on this post, and still not even a decision as to where to start with the project. I dunno what you're talking about either, how the end of development for tidesdk means it's not good enough. It's a simple, single page website that does regex. Do you foresee this project ever becoming something that's so complicated, that a roughly current version of webkit wouldn't be sufficient for it? Or is it just that you guys don't know any languages for developing native applications? Even using CEF in C++, it's a handful of lines of code to have this working client side.....

**Comment by TechnikEmpire** [comment]
Pardon the frustration, I come along finding a thread with peaked interest in contributing, only to get stone walled. I made multiple suggestions for what could be used, the only response I can get back seems to be **** swinging and debating semantics. So yeah, frustrated, too old for it, when you grow up pissing contests get old. Lost interest, no contribution, cya.

**Comment by lannymcnie** [comment]
Sorry you felt dismissed. It might not be immediately clear that we have already evaluated several tools for a desktop version, so we have already been through this internally.  The need for a version that runs offline has been raised, but only by a tiny percentage of the users, so it is not a high priority. 

In the mean time, we aren't anxious to build it with an SDK that might not see any updates to issues we encounter. Please remember that this project is completely free, ad-free, and 100% (so far) built by our team. 

That said, if anyone wants to build a version with Tide, or any other desktop wrapper, we would be happy to evaluate, and integrate it into the source here. This is part of why we released it open source. If it is in fact a handful of lines of code, then feel free to take a stab at it yourself, rather than prescribing what our team should focus our efforts on.

Again, appreciate the feedback, and I don't think there was any ill will intended here. 
Cheers.

**Comment by Dinesh-Ramakrishnan** [comment]
+1 for Offline Tool

**Comment by mul14** [comment]
How about [Electron](https://github.com/atom/electron)? Have you try it? It used by Slack, Facebook Nuclide, and Microsoft Visual Code.

I just experiment several hours ago https://github.com/mul14/regexr/tree/electron-test

**Comment by gskinner** [comment]
I think looking at Electron makes a lot of sense. We'll give it a go soon.

**Comment by papiveron** [comment]
Hi,

Please I clone the repository and installed with npm. But I still can't figure out how to run the regexr desktop version on my computer.

Is it really possible or we can use only the online version? If using the desktop is possible, how to get there. The documentation is not clear about that.

Thank you so much.

Regards.
